{% set version = "1.14.0" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz
  sha256: c45d99134bb07600e916537c51c22e87f9e0c44b05d71018ab4907e195f007ce

build:
  number: 200
  skip: true  # [win32 or (win and py27)]
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    # libgcc-ng should be a dependecy of libgfortran
    # until this is fixed add libgcc explicitly
    - libgcc-ng         # [linux and blas_impl == 'openblas']
    - git
  host:
    - cython
    - python
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  requires:
    - nose
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - nomkl  # [x86 and blas_impl != 'mkl']
  commands:
    - f2py -h
    - python -c "import numpy; numpy.show_config()"
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'
  description: |
    NumPy is the fundamental package needed for scientific computing with Python.
  doc_url: https://docs.scipy.org/doc/numpy-1.14.0/reference/
  dev_url: https://github.com/numpy/numpy
  dev_source_url: https://github.com/numpy/numpy/tree/master/doc

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
