{% set version = "1.9.3" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  sha256: c3b74d3b9da4ceb11f66abd21e117da8cf584b63a0efbd01a9b7e91b693fbbd6
  patches:
    - mklfft.patch
    # customize gfortran executable that gets looked for to use our GFORTRAN env var
    - gfortran_alias.patch
    # fix fortran regex for ctng compilers
    - fortran_regex.patch
    # make intel fortran version detection a little easier
    - force_intel_compiler_version.patch

build:
  number: 2
  # conda 4.4+ can use this
  requires_features:
    blas: {{ blas_impl }}
  # this is for conda 4.3 and below
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - cython
    - python
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas    # [blas_impl == 'openblas']
  run:
    - python
    # openblas or mkl runtime included with run_exports

test:
  requires:
    - nose
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
