{% set version = "1.14.2" %}

package:
  name: numpy
  version: {{ version }}

source:
  fn: numpy-{{ version }}.tar.gz
  url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  sha256: ddbcda194f49e0cf0663fa8131cb9d7a3b876d14dea0047d3c5fdfaf20adbb40
  patches:
    - mklfft.patch

build:
  number: 1
  features:
    - nomkl    # [x86 and nomkl]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - cython
    - python
    - setuptools
    - mkl-devel                   # [not nomkl]
    - openblas                    # [nomkl]
  run:
    - python
    - openblas                    # [nomkl]
    # mkl runtime added by run_exports for mkl-devel

test:
  requires:
    - nose
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
