{% set version = "1.10.4" %}

{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  fn: numpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  md5: aed294de0aa1ac7bd3f9745f4f1968ad
  patches:
    # Adds a patch to workaround a known test failure on Linux.
    # This patch comes from an accepted PR to the 1.10.x maintenance
    # branch. However, it is unclear whether there will be a 1.10.5
    # release. If there is, this can be dropped.
    # 
    # Link below for reference.
    #
    # https://github.com/numpy/numpy/pull/7657
    #
    - numpy_PR_7657.diff

build:
  number: 202
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cython
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*

test:
  requires:
    - nose
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: array processing for numbers, strings, records, and objects.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
