{% set version = "1.7.2" %}
{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  sha256: f963f6a5e21438dede6b4412cf9aaa230c145038a6d234aefdd70d20152f8d53

build:
  number: 202
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: True  # [win or py35 or py36]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*  # [linux]
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*  # [linux]

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
