{% set version = "1.9.3" %}

package:
  name: numpy
  version: {{ version }}

source:
  url: https://github.com/numpy/numpy/archive/v{{ version }}.tar.gz
  sha256: c678dc4f7f4801a25c139c1131a97d9187cf645de276e1b3c74e2eadb5b5c961
  patches:
    - mklfft.patch
    # customize gfortran executable that gets looked for to use our GFORTRAN env var
    - gfortran_alias.patch    # [linux]
    # fix fortran regex for ctng compilers
    - fortran_regex.patch     # [linux]
    # backport https://github.com/numpy/numpy/pull/7634 to support $CC
    - correct-c-compiler-customization-in-system_info.py.patch

build:
  number: 3
  skip: True  # [blas_impl == 'openblas' and win]
  # conda 4.4+ can use this
  requires_features:
    blas: {{ blas_impl }}
  # this is for conda 4.3 and below
  features:
    - nomkl    # [x86 and blas_impl != 'mkl']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - cython
    - python
    - mkl-devel  {{ mkl }}  # [blas_impl == 'mkl']
    - openblas-devel {{ openblas }}  # [blas_impl == 'openblas']
  run:
    - python
    # openblas or mkl runtime included with run_exports

test:
  requires:
    - nose
    - nomkl  # [blas_impl == 'openblas']
  commands:
    - f2py -h
    - conda inspect linkages -p $PREFIX numpy  # [not win]
    - conda inspect objects -p $PREFIX numpy  # [osx]
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Array processing for numbers, strings, records, and objects.'

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
